openapi: 3.0.3
info:
  title: Brain Agriculture API
  description: API para gerenciamento de produtores rurais e suas propriedades
  version: 1.0.0
  contact:
    name: Brain Agriculture
    email: contato@brainagriculture.com
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT

servers:
  - url: http://localhost:3000/api/v1
    description: Servidor de desenvolvimento
  - url: https://api.brainagriculture.com/v1
    description: Servidor de produção

paths:
  /producers:
    get:
      summary: Lista todos os produtores
      description: Retorna uma lista paginada de todos os produtores rurais cadastrados
      tags:
        - Produtores
      parameters:
        - name: page
          in: query
          description: Número da página
          required: false
          schema:
            type: integer
            default: 1
            minimum: 1
        - name: limit
          in: query
          description: Número de itens por página
          required: false
          schema:
            type: integer
            default: 10
            minimum: 1
            maximum: 100
        - name: search
          in: query
          description: Termo de busca (nome ou CPF/CNPJ)
          required: false
          schema:
            type: string
      responses:
        "200":
          description: Lista de produtores retornada com sucesso
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: array
                    items:
                      $ref: "#/components/schemas/Producer"
                  pagination:
                    $ref: "#/components/schemas/Pagination"
        "400":
          $ref: "#/components/responses/BadRequest"
        "500":
          $ref: "#/components/responses/InternalServerError"

    post:
      summary: Cadastra um novo produtor
      description: Cria um novo produtor rural com suas propriedades
      tags:
        - Produtores
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/ProducerCreate"
      responses:
        "201":
          description: Produtor criado com sucesso
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Producer"
        "400":
          $ref: "#/components/responses/BadRequest"
        "422":
          $ref: "#/components/responses/ValidationError"
        "500":
          $ref: "#/components/responses/InternalServerError"

  /producers/{id}:
    get:
      summary: Busca um produtor específico
      description: Retorna os dados de um produtor específico pelo ID
      tags:
        - Produtores
      parameters:
        - name: id
          in: path
          required: true
          description: ID do produtor
          schema:
            type: string
            format: uuid
      responses:
        "200":
          description: Produtor encontrado
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Producer"
        "404":
          $ref: "#/components/responses/NotFound"
        "500":
          $ref: "#/components/responses/InternalServerError"

    put:
      summary: Atualiza um produtor
      description: Atualiza os dados de um produtor existente
      tags:
        - Produtores
      parameters:
        - name: id
          in: path
          required: true
          description: ID do produtor
          schema:
            type: string
            format: uuid
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/ProducerUpdate"
      responses:
        "200":
          description: Produtor atualizado com sucesso
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Producer"
        "400":
          $ref: "#/components/responses/BadRequest"
        "404":
          $ref: "#/components/responses/NotFound"
        "422":
          $ref: "#/components/responses/ValidationError"
        "500":
          $ref: "#/components/responses/InternalServerError"

    delete:
      summary: Remove um produtor
      description: Remove um produtor e todas suas propriedades
      tags:
        - Produtores
      parameters:
        - name: id
          in: path
          required: true
          description: ID do produtor
          schema:
            type: string
            format: uuid
      responses:
        "204":
          description: Produtor removido com sucesso
        "404":
          $ref: "#/components/responses/NotFound"
        "500":
          $ref: "#/components/responses/InternalServerError"

  /dashboard:
    get:
      summary: Estatísticas do dashboard
      description: Retorna estatísticas gerais e dados para gráficos
      tags:
        - Dashboard
      responses:
        "200":
          description: Estatísticas retornadas com sucesso
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/DashboardStats"
        "500":
          $ref: "#/components/responses/InternalServerError"

  /validation/cpf-cnpj:
    post:
      summary: Valida CPF ou CNPJ
      description: Valida se um CPF ou CNPJ é válido
      tags:
        - Validação
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                document:
                  type: string
                  description: CPF ou CNPJ para validação
                  example: "123.456.789-09"
              required:
                - document
      responses:
        "200":
          description: Resultado da validação
          content:
            application/json:
              schema:
                type: object
                properties:
                  isValid:
                    type: boolean
                    description: Se o documento é válido
                  documentType:
                    type: string
                    enum: [CPF, CNPJ]
                    description: Tipo do documento
                  formatted:
                    type: string
                    description: Documento formatado
        "400":
          $ref: "#/components/responses/BadRequest"

components:
  schemas:
    Producer:
      type: object
      properties:
        id:
          type: string
          format: uuid
          description: ID único do produtor
        cpfCnpj:
          type: string
          description: CPF ou CNPJ do produtor
          example: "123.456.789-09"
        name:
          type: string
          description: Nome completo do produtor
          example: "João Silva"
        farms:
          type: array
          items:
            $ref: "#/components/schemas/Farm"
          description: Lista de propriedades do produtor
        createdAt:
          type: string
          format: date-time
          description: Data de criação do registro
        updatedAt:
          type: string
          format: date-time
          description: Data da última atualização
      required:
        - id
        - cpfCnpj
        - name
        - farms

    ProducerCreate:
      type: object
      properties:
        cpfCnpj:
          type: string
          description: CPF ou CNPJ do produtor
          example: "123.456.789-09"
        name:
          type: string
          description: Nome completo do produtor
          example: "João Silva"
        farms:
          type: array
          items:
            $ref: "#/components/schemas/FarmCreate"
          description: Lista de propriedades do produtor
      required:
        - cpfCnpj
        - name
        - farms

    ProducerUpdate:
      type: object
      properties:
        cpfCnpj:
          type: string
          description: CPF ou CNPJ do produtor
        name:
          type: string
          description: Nome completo do produtor
        farms:
          type: array
          items:
            $ref: "#/components/schemas/FarmUpdate"
          description: Lista de propriedades do produtor

    Farm:
      type: object
      properties:
        id:
          type: string
          format: uuid
          description: ID único da fazenda
        name:
          type: string
          description: Nome da fazenda
          example: "Fazenda São João"
        city:
          type: string
          description: Cidade da fazenda
          example: "Londrina"
        state:
          type: string
          description: Estado da fazenda
          example: "PR"
        totalArea:
          type: number
          format: float
          description: Área total em hectares
          example: 500.0
        agriculturalArea:
          type: number
          format: float
          description: Área agricultável em hectares
          example: 300.0
        vegetationArea:
          type: number
          format: float
          description: Área de vegetação em hectares
          example: 200.0
        crops:
          type: array
          items:
            $ref: "#/components/schemas/Crop"
          description: Lista de culturas plantadas
      required:
        - id
        - name
        - city
        - state
        - totalArea
        - agriculturalArea
        - vegetationArea
        - crops

    FarmCreate:
      type: object
      properties:
        name:
          type: string
          description: Nome da fazenda
        city:
          type: string
          description: Cidade da fazenda
        state:
          type: string
          description: Estado da fazenda
        totalArea:
          type: number
          format: float
          description: Área total em hectares
        agriculturalArea:
          type: number
          format: float
          description: Área agricultável em hectares
        vegetationArea:
          type: number
          format: float
          description: Área de vegetação em hectares
        crops:
          type: array
          items:
            $ref: "#/components/schemas/CropCreate"
          description: Lista de culturas plantadas
      required:
        - name
        - city
        - state
        - totalArea
        - agriculturalArea
        - vegetationArea
        - crops

    FarmUpdate:
      type: object
      properties:
        name:
          type: string
          description: Nome da fazenda
        city:
          type: string
          description: Cidade da fazenda
        state:
          type: string
          description: Estado da fazenda
        totalArea:
          type: number
          format: float
          description: Área total em hectares
        agriculturalArea:
          type: number
          format: float
          description: Área agricultável em hectares
        vegetationArea:
          type: number
          format: float
          description: Área de vegetação em hectares
        crops:
          type: array
          items:
            $ref: "#/components/schemas/CropUpdate"
          description: Lista de culturas plantadas

    Crop:
      type: object
      properties:
        id:
          type: string
          format: uuid
          description: ID único da cultura
        name:
          type: string
          description: Nome da cultura
          example: "Soja"
        harvest:
          type: string
          description: Safra da cultura
          example: "Safra 2021"
        area:
          type: number
          format: float
          description: Área plantada em hectares
          example: 150.0
      required:
        - id
        - name
        - harvest
        - area

    CropCreate:
      type: object
      properties:
        name:
          type: string
          description: Nome da cultura
        harvest:
          type: string
          description: Safra da cultura
        area:
          type: number
          format: float
          description: Área plantada em hectares
      required:
        - name
        - harvest
        - area

    CropUpdate:
      type: object
      properties:
        name:
          type: string
          description: Nome da cultura
        harvest:
          type: string
          description: Safra da cultura
        area:
          type: number
          format: float
          description: Área plantada em hectares

    DashboardStats:
      type: object
      properties:
        totalFarms:
          type: integer
          description: Total de fazendas cadastradas
          example: 5
        totalHectares:
          type: number
          format: float
          description: Total de hectares registrados
          example: 2500.0
        totalProducers:
          type: integer
          description: Total de produtores cadastrados
          example: 3
        totalCrops:
          type: integer
          description: Total de culturas plantadas
          example: 12
        stateDistribution:
          type: array
          items:
            $ref: "#/components/schemas/ChartData"
          description: Distribuição por estado
        cropDistribution:
          type: array
          items:
            $ref: "#/components/schemas/ChartData"
          description: Distribuição por cultura
        landUseDistribution:
          type: array
          items:
            $ref: "#/components/schemas/ChartData"
          description: Distribuição por uso do solo

    ChartData:
      type: object
      properties:
        name:
          type: string
          description: Nome da categoria
          example: "PR"
        value:
          type: number
          format: float
          description: Valor da categoria
          example: 1200.0
        percentage:
          type: number
          format: float
          description: Percentual da categoria
          example: 48.0

    Pagination:
      type: object
      properties:
        page:
          type: integer
          description: Página atual
          example: 1
        limit:
          type: integer
          description: Itens por página
          example: 10
        total:
          type: integer
          description: Total de itens
          example: 25
        totalPages:
          type: integer
          description: Total de páginas
          example: 3

  responses:
    BadRequest:
      description: Requisição inválida
      content:
        application/json:
          schema:
            type: object
            properties:
              error:
                type: string
                example: "Parâmetros inválidos"
              message:
                type: string
                example: "Os dados fornecidos são inválidos"

    NotFound:
      description: Recurso não encontrado
      content:
        application/json:
          schema:
            type: object
            properties:
              error:
                type: string
                example: "Not Found"
              message:
                type: string
                example: "Produtor não encontrado"

    ValidationError:
      description: Erro de validação
      content:
        application/json:
          schema:
            type: object
            properties:
              error:
                type: string
                example: "Validation Error"
              message:
                type: string
                example: "Dados inválidos"
              details:
                type: array
                items:
                  type: object
                  properties:
                    field:
                      type: string
                      example: "cpfCnpj"
                    message:
                      type: string
                      example: "CPF/CNPJ inválido"

    InternalServerError:
      description: Erro interno do servidor
      content:
        application/json:
          schema:
            type: object
            properties:
              error:
                type: string
                example: "Internal Server Error"
              message:
                type: string
                example: "Erro interno do servidor"

tags:
  - name: Produtores
    description: Operações relacionadas aos produtores rurais
  - name: Dashboard
    description: Estatísticas e dados para dashboard
  - name: Validação
    description: Validações de dados
